### PR TITLE
chore: enable arm64 build

### PR DESCRIPTION
**Pull request by benoitf**
Change-Id: I9a0e0bee7f36bbb999fe5afe789965d600c60cea
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

fixes https://github.com/containers/podman-desktop/issues/1069

### CODE REVIEW

**Comment by ymurawski** [comment]
0C417D7C-900E-41AA-977F-DB4565DCDE60
54718DD6-6F8F-44C2-9F6B-572E637F7525

**Comment by ymurawski** [comment]
Works 🙃

**Comment by ymurawski** [comment]
Will podman desktop auto update itself and the containers?

**Comment by benoitf** [comment]
@ymurawski so after merging the PR, if you install it from flathub (not from a PR) then yes you've updates that are available

**Pull request merged**
